name: CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar dependências
      run: |
        if [ -f package.json ]; then
          npm install
        else
          echo "Sem dependências a instalar"
        fi

    - name: Executar Lint
      if: ${{ hashFiles('**/*.js') != '' }}
      run: |
        npm install eslint --save-dev
        npx eslint . || true

    - name: Build da aplicação
      run: |
        if [ -f package.json ]; then
          npm run build || echo "Sem script de build definido"
        else
          echo "Projeto estático - Sem build necessário"
        fi
